version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dep_order_service_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3550:3550"
    depends_on:
      - mysql
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: dep_order_service_db

volumes:
  mysql_data:
